[build]
  # Build command (if you had a build process)
  # command = "npm run build"
  
  # Folder to deploy - Updated to use netlify-deploy folder
  publish = "netlify-deploy"

[build.environment]
  # Node version for any build processes
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Special headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Special headers for CSS and JS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image optimization
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SEO and user experience
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Form handling (if you add forms later)
# [[redirects]]
#   from = "/contact"
#   to = "/contact.html"
#   status = 200

# 404 redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
